In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [26]:
allDF1 = pd.read_excel('../../fixedData/allArea1.xlsx', header=[0,1])
allDF1.fillna(method='ffill', inplace=True)
allDF1

   행정구역별                         산업별        사업체구분별     2020              2021  \
   행정구역별                         산업별        사업체구분별 사업체수 (개) 종사자수 (명) 사업체수 (개)
0     서울        　　　　　　소프트웨어 개발 및 공급업             계    21654   186005    21981
1     서울        　　　　　　소프트웨어 개발 및 공급업         단독사업체    20361   140418    20174
2     서울        　　　　　　소프트웨어 개발 및 공급업       본사,본점 등      764    32520     1022
3     서울        　　　　　　소프트웨어 개발 및 공급업  공장,지사(점),영업소      529    13067      785
4     서울  　　　컴퓨터 프로그래밍, 시스템 통합 및 관리업             계     9536    97675     9822
..   ...                         ...           ...      ...      ...      ...
91    강원  　　　컴퓨터 프로그래밍, 시스템 통합 및 관리업  공장,지사(점),영업소       14       59       13
92    강원                   　　　정보서비스업             계      106      728      301
93    강원                   　　　정보서비스업         단독사업체       98      215      295
94    강원                   　　　정보서비스업       본사,본점 등        3      494        2
95    강원                   　　　정보서비스업  공장,지사(점),영업소        5       19        4

                2022
   종사자수 (명) 사업체수 (개) 종사자수 (명)
0    206675    23550   223246
1    148950    21457   155704
2     40281     1118    50663
3     17444      975    16879
4    100768    10037   103343
..      ...      ...      ...
91       78       11       72
92     1003      137      837
93      464      131      283
94        X        2        X
95       18        4       19

[96 rows x 9 columns]

In [27]:
allDF2 = pd.read_excel('../../fixedData/allArea2.xlsx', header=[0,1])
allDF2.fillna(method='ffill', inplace=True)
allDF2

    행정구역별                   산업별      종사자규모별     2020              2021  \
    행정구역별                   산업별      종사자규모별 사업체수 (개) 종사자수 (명) 사업체수 (개)
0      서울  　　　　　　소프트웨어 개발 및 공급업           계    21654   186005    21981
1      서울  　　　　　　소프트웨어 개발 및 공급업      1 - 4명    15652    23036    15497
2      서울  　　　　　　소프트웨어 개발 및 공급업      5 - 9명     2478    16301     2627
3      서울  　　　　　　소프트웨어 개발 및 공급업    10 - 19명     1701    22869     1821
4      서울  　　　　　　소프트웨어 개발 및 공급업    20 - 49명     1164    34573     1296
..    ...                   ...         ...      ...      ...      ...
169    강원             　　　정보서비스업      5 - 9명        8       47        3
170    강원             　　　정보서비스업    10 - 19명        2        X        5
171    강원             　　　정보서비스업    20 - 49명        1        X        3
172    강원             　　　정보서비스업  300 - 499명        1        X        -
173    강원             　　　정보서비스업  500 - 999명        -        -        1

                 2022
    종사자수 (명) 사업체수 (개) 종사자수 (명)
0     206675    23550   223246
1      23583    17009    25789
2      17248     2504    16550
3      24056     1825    24280
4      38628     1423    42705
..       ...      ...      ...
169       17        3       17
170       67        5       74
171       71        2        X
172        -        -        -
173        X        1        X

[174 rows x 9 columns]

In [23]:
seoulCurrent = pd.read_excel('../../fixedData/seoulCurrent.xlsx', header=[0,1])
seoulCurrent

C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                   산업별(1)     2018                                          \
                   산업별(1) 현재인원 (명) 해당직무 입사 3년차 연봉 (만원) 고용안전성 (점) 발전가능성 (점)
0                       계   255928                4232       3.8       3.8
1                      기계     2838                5397       3.4       3.5
2                   디스플레이      111                3590       3.5       3.8
3                     반도체      837                4493       3.4       3.5
4                  바이오ㆍ헬스     1597                3905       3.7       3.7
5                      섬유     4672                3272       3.6       3.4
6                     자동차        -                   -         -         -
7                      전자     8855                3773       3.7       3.7
8                      조선        -                   -         -         -
9                      철강      174                3775       3.5       3.5
10                     화학      943                3983         4       3.7
11                  소프트웨어    94855                3957       3.9         4
12                IT 비즈니스    14261                3946       3.8       3.8
13                식료품 제조업       69                5502         3         3
14                 음료 제조업       96                3117         4         4
15                 담배 제조업        -                   -         -         -
16        가죽, 가방 및 신발 제조업      396                3186       3.4       3.4
17     목재 및 나무제품 제조업;가구제외        -                   -         -         -
18     펄프, 종이 및 종이 제품 제조업      472                4293       3.4       3.3
19          인쇄 및 기록매체 복제업     1890                3474       3.1       3.1
20           비금속 광물제품 제조업       37                3467         4       3.7
21  금속가공제품 제조업;기계 및 가구 제외       64                5750         3         3
22                 가구 제조업      102                3348         3         3
23              기타 제품 제조업     1068                4022       3.4       3.4
24                  연구개발업    13784                4633         4       4.1
25                 전문서비스업    18782                5913       3.6       3.7
26       건축기술, 엔지니어링 과학기술    65912                4507       3.9       3.7
27    기타 전문, 과학 및 기술 서비스업     2625                3247       3.6       3.7
28             영상/오디오 제작업     2380                3416       3.6       3.6
29               우편 및 통신업    10559                4928       3.7       3.6
30            환경 정화 및 복원업       88                3722       3.8         4
31             임대업; 부동산제외      512                3609       3.6       3.6
32      사업시설 관리 및 조경 서비스업     4795                3464         4       3.9
33              사업지원 서비스업     1157                4695       3.9       3.8
34                 교육서비스업       50                3611         3         3
35                    보건업     1948                5027       3.7       3.6

       2019                                             2020  ...            \
   현재인원 (명) 해당직무 입사 3년차 연봉 (만원) 고용안전성 (점) 발전가능성 (점) 현재인원 (명)  ... 고용안전성 (점)
0    256172                4029       3.6       3.7   252893  ...       3.7
1      7336                3404       3.3       3.4     3310  ...       3.6
2       623                3940       3.2       3.3      109  ...         4
3      3762                3933       3.5       3.4     1111  ...       3.9
4      2157                3648       3.4       3.4     1433  ...       3.2
5      4019                3614       3.4       3.4     3788  ...       3.4
6       857                3583       3.8       3.9       66  ...         5
7     10849                3506       3.5       3.4     7375  ...       3.5
8         -                   -         -         -        -  ...         -
9       587                3593       3.1         3      138  ...       3.3
10     2894                3488       3.3       3.3     1506  ...       3.9
11    96101                3990       3.5       3.6   104831  ...       3.5
12    13316                3839       3.5       3.7    14801  ...       4.1
13      150                3405       3.5       3.7      129  ...       4.5
14      153                3417       3.2       3.3       11  ...         3
15        -                   -         -         -        -  ...         -
16      696                3233       3.1         3      608  ...       3.5
17        -                   -         -         -        -  ...         -
18      630                3442         3         3      275  ...       3.5
19     1663                3313       3.7       3.3     1850  ...       3.3
20      138                3572       3.4       3.7      136  ...       3.3
21     2406                3910       3.8       3.8      632  ...       3.3
22      565                4259         3         3       62  ...       3.8
23     1944                3543       3.5       3.5     2373  ...       3.6
24    22651                5152       4.4       4.4    24961  ...       4.1
25    17199                4801       3.7       3.9    17129  ...       3.8
26    46591                4008       3.7       3.7    50467  ...         4
27     2260                4012       3.6       3.7     1474  ...         4
28     2719                4019         4       3.6     2334  ...       3.9
29     3978                4453       3.7       3.7     4140  ...       3.9
30       33                4500         5         5       41  ...       4.4
31      532                3711       3.3       3.1      698  ...       3.5
32     6467                3901       3.6       3.7     4058  ...       3.8
33      651                4033       3.5       3.5      802  ...       3.9
34      195                3949       4.2       4.3       58  ...       4.1
35     2051                4571       3.8       3.7     2186  ...       3.5

                 2021                                             2022  \
   발전가능성 (점) 현재인원 (명) 해당직무 입사 3년차 연봉 (만원) 고용안전성 (점) 발전가능성 (점) 현재인원 (명)
0        3.8   257450                4313       3.6       3.7   274782
1        3.7     4556                3943       3.8       3.8     5132
2        4.1      244                4266       3.7       3.7      163
3        3.9     1101                4328       3.3       3.3      812
4        3.3     1808                4436       3.8       3.8     1814
5        3.4     5002                4275       3.6       3.6     4726
6        4.5       81                3598       3.9       3.9       59
7        3.7     9401                4473       3.8       3.8     9265
8          -        -                   -         -         -        -
9        3.5      127                2946       3.3       3.1      103
10       3.7     1210                4045       3.4       3.7     1895
11       3.8   105355                4345       3.5       3.8   108308
12       4.1    14229                3900       3.6       3.6    14963
13       4.5      384                3493       3.4       3.2      149
14         3       32                2800         3         3       21
15         -        -                   -         -         -        -
16       3.4      913                3390       3.5       3.5      669
17         -        -                   -         -         -       21
18       3.3      155                3966       3.5       3.2      469
19       3.3     2044                3122       3.7       3.6     2345
20       3.3        -                   -         -         -       85
21       3.2       96                2775       3.3       3.3      890
22         3      169                4692       4.1       4.1       39
23       3.7     1606                3646       3.5       3.6      694
24       4.2    22404                4918       3.8       3.9    41036
25       3.8    17607                4855       3.4       3.6    19661
26         4    51355                4496       3.7       3.8    40590
27       3.9     2174                4088       3.6       3.7     2962
28       3.9     1787                3760       3.3       3.4     1414
29         4     2657                5093       3.6       3.6     4584
30       4.4      127                3823       3.7       3.7       32
31       3.8      741                4559       3.6       3.7      290
32       3.6     6515                3583       3.5       3.6     6959
33       3.8     1418                4299       3.6       3.7     1436
34       4.2      185                3802       3.7       3.6      192
35       3.5     1968                4018       3.5       3.5     3004


   해당직무 입사 3년차 연봉 (만원) 고용안전성 (점) 발전가능성 (점)
0                 4343       3.5       3.5
1                 3688       3.7       3.4
2                 3660       3.8       3.3
3                 3866       3.2       3.4
4                 3807       3.1       3.3
5                 3359       3.4       3.6
6                 3200         3         2
7                 3566         3       3.3
8                    -         -         -
9                 3850         4         4
10                3702       3.2       3.3
11                4452       3.6       3.7
12                4164       3.4       3.5
13                3826       3.1       3.1
14                3863         3         3
15                   -         -         -
16                3747       3.3       3.3
17                3700         3         3
18                3783       3.3       3.4
19                3372       3.1       3.1
20                4556       3.3       3.3
21                3312       3.2       3.2
22                3817         4         4
23                3895       3.2       3.4
24                4519       3.5       3.7
25                4574       3.3       3.4
26                4211       3.4       3.5
27                3789       3.5       3.5
28                3817       3.4       3.5
29                4046       3.2       3.3
30                4275         4       3.4
31                3810       3.2       3.3
32                4284       3.3       3.7
33                3858       3.5       3.3
34                4410       3.6       3.8
35                6173       3.3       3.3

[36 rows x 21 columns]

In [24]:
seoulCurrent.columns

MultiIndex([('산업별(1)',              '산업별(1)'),
            (  '2018',            '현재인원 (명)'),
            (  '2018', '해당직무 입사 3년차 연봉 (만원)'),
            (  '2018',           '고용안전성 (점)'),
            (  '2018',           '발전가능성 (점)'),
            (  '2019',            '현재인원 (명)'),
            (  '2019', '해당직무 입사 3년차 연봉 (만원)'),
            (  '2019',           '고용안전성 (점)'),
            (  '2019',           '발전가능성 (점)'),
            (  '2020',            '현재인원 (명)'),
            (  '2020', '해당직무 입사 3년차 연봉 (만원)'),
            (  '2020',           '고용안전성 (점)'),
            (  '2020',           '발전가능성 (점)'),
            (  '2021',            '현재인원 (명)'),
            (  '2021', '해당직무 입사 3년차 연봉 (만원)'),
            (  '2021',           '고용안전성 (점)'),
            (  '2021',           '발전가능성 (점)'),
            (  '2022',            '현재인원 (명)'),
            (  '2022', '해당직무 입사 3년차 연봉 (만원)'),
            (  '2022',           '고용안전성 (점)'),
            (  '2022',           '발전가능성 (점)')],
           )

In [25]:
seoulNeed = pd.read_excel('../../fixedData/seoulNeed.xlsx', header=[0,1])
seoulExpect = pd.read_excel('../../fixedData/seoulExpect.xlsx', header=[0,1])
ggCurrent = pd.read_excel('../../fixedData/ggCurrent.xlsx', header=[0,1])
ggNeed = pd.read_excel('../../fixedData/ggNeed.xlsx', header=[0,1])
ggExpect = pd.read_excel('../../fixedData/ggExpect.xlsx', header=[0,1])
daeguCurrent = pd.read_excel('../../fixedData/daeguCurrent.xlsx', header=[0,1])
daeguNeed = pd.read_excel('../../fixedData/daeguNeed.xlsx', header=[0,1])
daeguExpect = pd.read_excel('../../fixedData/daeguExpect.xlsx', header=[0,1])

C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
C:\Users\kdp\anaconda3\envs\My_38\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")